### ISSUE TITLE
CUDA out of memory while running visualize.py in 2 x Tesla K80 (12 + 12 GB) VM

### ISSUE THREAD

**Issue by sandeepnmenon** [mit-han-lab/e3d#21]
I am trying to use the pretrained model 'SemanticKITTI_val_SPVCNN@119GMACs' to segment my point cloud of shape 
(566151, 4).
I was getting the following error in my 
```
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 00000000:B3:00.0  On |                  N/A |
| 22%   45C    P8    16W / 250W |    532MiB / 12211MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

```
`RuntimeError: CUDA out of memory. Tried to allocate 162.00 MiB (GPU 0; 11.93 GiB total capacity; 10.29 GiB already allocated; 128.81 MiB free; 10.67 GiB reserved in total by PyTorch)`
on running the command
**python visualize.py --model SemanticKITTI_val_SPVCNN@119GMACs**

Now I am trying in my VM with 2 x Tesla K80 GPUs.
```
|===============================+======================+======================|
|   0  Tesla K80           On   | 00008FA5:00:00.0 Off |                    0 |
| N/A   34C    P8    30W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 0000BC37:00:00.0 Off |                    0 |
| N/A   41C    P8    27W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

```
Using the command
**torchpack dist-run -np 2 python visualize.py --model SemanticKITTI_val_SPVCNN@119GMACs**
to use both the GPUs. Still I am getting the out of memory error
`RuntimeError: CUDA out of memory. Tried to allocate 60.00 MiB (GPU 0; 11.17 GiB total capacity; 5.47 GiB already allocated; 46.69 MiB free; 5.62 GiB reserved in total by PyTorch)`
And it seems like only one GPU is getting used on watching "nvidia-smi' and also from the error message.

How much single GPU space is required to run inference of the SPVCNN@119GMACs model on a point cloud of size (566151, 4)?
Can we use torchpack to split inference in multiple GPUs? If yes what is wrong with my command mentioned above?

Thank you

**Comment by kentangSJTU** [comment]
Hi,

I think your point cloud is much larger than the typical size (which is ~100k x 4), a possible way to reduce memory consumption is to wrap lines 175 to 196 of the `visualize.py` file with
```python
with torch.no_grad():
```

I believe this strategy should work for you.

Best,
Haotian

**Comment by sandeepnmenon** [comment]
> Hi,
> 
> I think your point cloud is much larger than the typical size (which is ~100k x 4), a possible way to reduce memory consumption is to wrap lines 175 to 196 of the `visualize.py` file with
> 
> ```python
> with torch.no_grad():
> ```
> 
> I believe this strategy should work for you.
> 
> Best,
> Haotian

Thank you @kentangSJTU 
This worked and the results are amazing!. I was downsampling and upsampling to get around this. However the torch.no_grad(): did the trick.
